// Helper: get esoteric target for a given piece and hexNum using the nested lookup structure
export function getEsotericTarget(piece, hexNum) {
  console.log('[esotericMoves] getEsotericTarget called:', { piece, hexNum });
  const entry = esotericMovesByHexNum[hexNum]?.[piece];
  if (!entry || entry.esotericTarget == null) {
    console.log('[esotericMoves] No esoteric entry found for', { piece, hexNum });
    return null;
  }
  const target = positionMap.find(p => p.hexNum === entry.esotericTarget);
  if (!target) {
    console.log('[esotericMoves] No target found for esotericTarget:', entry.esotericTarget);
    return null;
  }
  console.log('[esotericMoves] Esoteric target found:', { piece, hexNum, target });
  return {
    hexNum: entry.esotericTarget,
    row: target.row,
    col: target.col,
    coord: target.coord
  };
}
import { positionMap } from './positionMap.mjs';

export const esotericMoves = [
  { hexNum: 0, piece: "BK", esotericTarget: 1 },
  { hexNum: 0, piece: "BQ", esotericTarget: 2 },
  { hexNum: 0, piece: "BB", esotericTarget: 4 },
  { hexNum: 0, piece: "BN", esotericTarget: 8 },
  { hexNum: 0, piece: "BR", esotericTarget: 16 },
  { hexNum: 0, piece: "BP", esotericTarget: 32 },
  { hexNum: 0, piece: "WK", esotericTarget: null },
  { hexNum: 0, piece: "WQ", esotericTarget: null },
  { hexNum: 0, piece: "WB", esotericTarget: null },
  { hexNum: 0, piece: "WN", esotericTarget: null },
  { hexNum: 0, piece: "WR", esotericTarget: null },
  { hexNum: 0, piece: "WP", esotericTarget: null },

  { hexNum: 1, piece: "WK", esotericTarget: 0 },
  { hexNum: 1, piece: "BQ", esotericTarget: 3 },
  { hexNum: 1, piece: "BB", esotericTarget: 5 },
  { hexNum: 1, piece: "BN", esotericTarget: 9 },
  { hexNum: 1, piece: "BR", esotericTarget: 17 },
  { hexNum: 1, piece: "BP", esotericTarget: 33 },
  { hexNum: 1, piece: "BK", esotericTarget: null },
  { hexNum: 1, piece: "WQ", esotericTarget: null },
  { hexNum: 1, piece: "WB", esotericTarget: null },
  { hexNum: 1, piece: "WN", esotericTarget: null },
  { hexNum: 1, piece: "WR", esotericTarget: null },
  { hexNum: 1, piece: "WP", esotericTarget: null },

  { hexNum: 2, piece: "BK", esotericTarget: 3 },
  { hexNum: 2, piece: "WQ", esotericTarget: 0 },
  { hexNum: 2, piece: "BB", esotericTarget: 6 },
  { hexNum: 2, piece: "BN", esotericTarget: 10 },
  { hexNum: 2, piece: "BR", esotericTarget: 18 },
  { hexNum: 2, piece: "BP", esotericTarget: 34 },
  { hexNum: 2, piece: "WK", esotericTarget: null },
  { hexNum: 2, piece: "BQ", esotericTarget: null },
  { hexNum: 2, piece: "WB", esotericTarget: null },
  { hexNum: 2, piece: "WN", esotericTarget: null },
  { hexNum: 2, piece: "WR", esotericTarget: null },
  { hexNum: 2, piece: "WP", esotericTarget: null },

  { hexNum: 3, piece: "WK", esotericTarget: 2 },
  { hexNum: 3, piece: "WQ", esotericTarget: 1 },
  { hexNum: 3, piece: "BB", esotericTarget: 7 },
  { hexNum: 3, piece: "BN", esotericTarget: 11 },
  { hexNum: 3, piece: "BR", esotericTarget: 19 },
  { hexNum: 3, piece: "BP", esotericTarget: 35 },
  { hexNum: 3, piece: "BK", esotericTarget: null },
  { hexNum: 3, piece: "BQ", esotericTarget: null },
  { hexNum: 3, piece: "WB", esotericTarget: null },
  { hexNum: 3, piece: "WN", esotericTarget: null },
  { hexNum: 3, piece: "WR", esotericTarget: null },
  { hexNum: 3, piece: "WP", esotericTarget: null },

  { hexNum: 4, piece: "BK", esotericTarget: 5 },
  { hexNum: 4, piece: "BQ", esotericTarget: 6 },
  { hexNum: 4, piece: "WB", esotericTarget: 0 },
  { hexNum: 4, piece: "BN", esotericTarget: 12 },
  { hexNum: 4, piece: "BR", esotericTarget: 20 },
  { hexNum: 4, piece: "BP", esotericTarget: 36 },
  { hexNum: 4, piece: "WK", esotericTarget: null },
  { hexNum: 4, piece: "WQ", esotericTarget: null },
  { hexNum: 4, piece: "BB", esotericTarget: null },
  { hexNum: 4, piece: "WN", esotericTarget: null },
  { hexNum: 4, piece: "WR", esotericTarget: null },
  { hexNum: 4, piece: "WP", esotericTarget: null },

  { hexNum: 5, piece: "WK", esotericTarget: 4 },
  { hexNum: 5, piece: "BQ", esotericTarget: 7 },
  { hexNum: 5, piece: "WB", esotericTarget: 1 },
  { hexNum: 5, piece: "BN", esotericTarget: 13 },
  { hexNum: 5, piece: "BR", esotericTarget: 21 },
  { hexNum: 5, piece: "BP", esotericTarget: 37 },
  { hexNum: 5, piece: "BK", esotericTarget: null },
  { hexNum: 5, piece: "WQ", esotericTarget: null },
  { hexNum: 5, piece: "BB", esotericTarget: null },
  { hexNum: 5, piece: "WN", esotericTarget: null },
  { hexNum: 5, piece: "WR", esotericTarget: null },
  { hexNum: 5, piece: "WP", esotericTarget: null },

  { hexNum: 6, piece: "BK", esotericTarget: 7 },
  { hexNum: 6, piece: "WQ", esotericTarget: 4 },
  { hexNum: 6, piece: "WB", esotericTarget: 2 },
  { hexNum: 6, piece: "BN", esotericTarget: 14 },
  { hexNum: 6, piece: "BR", esotericTarget: 22 },
  { hexNum: 6, piece: "BP", esotericTarget: 38 },
  { hexNum: 6, piece: "WK", esotericTarget: null },
  { hexNum: 6, piece: "BQ", esotericTarget: null },
  { hexNum: 6, piece: "BB", esotericTarget: null },
  { hexNum: 6, piece: "WN", esotericTarget: null },
  { hexNum: 6, piece: "WR", esotericTarget: null },
  { hexNum: 6, piece: "WP", esotericTarget: null },

  { hexNum: 7, piece: "WK", esotericTarget: 6 },
  { hexNum: 7, piece: "WQ", esotericTarget: 5 },
  { hexNum: 7, piece: "WB", esotericTarget: 3 },
  { hexNum: 7, piece: "BN", esotericTarget: 15 },
  { hexNum: 7, piece: "BR", esotericTarget: 23 },
  { hexNum: 7, piece: "BP", esotericTarget: 39 },
  { hexNum: 7, piece: "BK", esotericTarget: null },
  { hexNum: 7, piece: "BQ", esotericTarget: null },
  { hexNum: 7, piece: "BB", esotericTarget: null },
  { hexNum: 7, piece: "WN", esotericTarget: null },
  { hexNum: 7, piece: "WR", esotericTarget: null },
  { hexNum: 7, piece: "WP", esotericTarget: null },

  { hexNum: 8, piece: "BK", esotericTarget: 9 },
  { hexNum: 8, piece: "BQ", esotericTarget: 10 },
  { hexNum: 8, piece: "BB", esotericTarget: 12 },
  { hexNum: 8, piece: "WN", esotericTarget: 0 },
  // GAME-LEVEL-DISABLED:{ hexNum: 8, piece: "BR", esotericTarget: 24 },
  { hexNum: 8, piece: "BP", esotericTarget: 40 },
  { hexNum: 8, piece: "WK", esotericTarget: null },
  { hexNum: 8, piece: "WQ", esotericTarget: null },
  { hexNum: 8, piece: "WB", esotericTarget: null },
  { hexNum: 8, piece: "BN", esotericTarget: null },
  { hexNum: 8, piece: "WR", esotericTarget: null },
  { hexNum: 8, piece: "WP", esotericTarget: null },

  { hexNum: 9, piece: "WK", esotericTarget: 8 },
  { hexNum: 9, piece: "BQ", esotericTarget: 11 },
  { hexNum: 9, piece: "BB", esotericTarget: 13 },
  { hexNum: 9, piece: "WN", esotericTarget: 1 },
  { hexNum: 9, piece: "BR", esotericTarget: 25 },
 // GAME-LEVEL-DISABLED: { hexNum: 9, piece: "BP", esotericTarget: 41 },
  { hexNum: 9, piece: "BK", esotericTarget: null },
  { hexNum: 9, piece: "WQ", esotericTarget: null },
  { hexNum: 9, piece: "WB", esotericTarget: null },
  { hexNum: 9, piece: "BN", esotericTarget: null },
  { hexNum: 9, piece: "WR", esotericTarget: null },
  { hexNum: 9, piece: "WP", esotericTarget: null },

  { hexNum: 10, piece: "BK", esotericTarget: 11 },
  { hexNum: 10, piece: "WQ", esotericTarget: 8 },
  { hexNum: 10, piece: "BB", esotericTarget: 14 },
  { hexNum: 10, piece: "WN", esotericTarget: 2 },
  { hexNum: 10, piece: "BR", esotericTarget: 26 },
 // GAME-LEVEL-DISABLED: { hexNum: 10, piece: "BP", esotericTarget: 42 },
  { hexNum: 10, piece: "WK", esotericTarget: null },
  { hexNum: 10, piece: "BQ", esotericTarget: null },
  { hexNum: 10, piece: "WB", esotericTarget: null },
  { hexNum: 10, piece: "BN", esotericTarget: null },
  { hexNum: 10, piece: "WR", esotericTarget: null },
  { hexNum: 10, piece: "WP", esotericTarget: null },

  { hexNum: 11, piece: "WK", esotericTarget: 10 },
  { hexNum: 11, piece: "WQ", esotericTarget: 9 },
  { hexNum: 11, piece: "BB", esotericTarget: 15 },
  { hexNum: 11, piece: "WN", esotericTarget: 3 },
  { hexNum: 11, piece: "BR", esotericTarget: 27 },
  // GAME-LEVEL-DISABLED:{ hexNum: 11, piece: "BP", esotericTarget: 43 },
  { hexNum: 11, piece: "BK", esotericTarget: null },
  { hexNum: 11, piece: "BQ", esotericTarget: null },
  { hexNum: 11, piece: "WB", esotericTarget: null },
  { hexNum: 11, piece: "BN", esotericTarget: null },
  { hexNum: 11, piece: "WR", esotericTarget: null },
  { hexNum: 11, piece: "WP", esotericTarget: null },

  { hexNum: 12, piece: "BK", esotericTarget: 13 },
  { hexNum: 12, piece: "BQ", esotericTarget: 14 },
  { hexNum: 12, piece: "WB", esotericTarget: 8 },
  { hexNum: 12, piece: "WN", esotericTarget: 4 },
  { hexNum: 12, piece: "BR", esotericTarget: 28 },
  // GAME-LEVEL-DISABLED:{ hexNum: 12, piece: "BP", esotericTarget: 44 },
  { hexNum: 12, piece: "WK", esotericTarget: null },
  { hexNum: 12, piece: "WQ", esotericTarget: null },
  { hexNum: 12, piece: "BB", esotericTarget: null },
  { hexNum: 12, piece: "BN", esotericTarget: null },
  { hexNum: 12, piece: "WR", esotericTarget: null },
  { hexNum: 12, piece: "WP", esotericTarget: null },

  { hexNum: 13, piece: "WK", esotericTarget: 12 },
  { hexNum: 13, piece: "BQ", esotericTarget: 15 },
  { hexNum: 13, piece: "WB", esotericTarget: 9 },
  { hexNum: 13, piece: "WN", esotericTarget: 5 },
  { hexNum: 13, piece: "BR", esotericTarget: 29 },
 // GAME-LEVEL-DISABLED: { hexNum: 13, piece: "BP", esotericTarget: 45 },
  { hexNum: 13, piece: "BK", esotericTarget: null },
  { hexNum: 13, piece: "WQ", esotericTarget: null },
  { hexNum: 13, piece: "BB", esotericTarget: null },
  { hexNum: 13, piece: "BN", esotericTarget: null },
  { hexNum: 13, piece: "WR", esotericTarget: null },
  { hexNum: 13, piece: "WP", esotericTarget: null },

  { hexNum: 14, piece: "BK", esotericTarget: 15 },
  { hexNum: 14, piece: "WQ", esotericTarget: 12 },
  { hexNum: 14, piece: "WB", esotericTarget: 10 },
  { hexNum: 14, piece: "WN", esotericTarget: 6 },
  { hexNum: 14, piece: "BR", esotericTarget: 30 },
  // GAME-LEVEL-DISABLED:{ hexNum: 14, piece: "BP", esotericTarget: 46 },
  { hexNum: 14, piece: "WK", esotericTarget: null },
  { hexNum: 14, piece: "BQ", esotericTarget: null },
  { hexNum: 14, piece: "BB", esotericTarget: null },
  { hexNum: 14, piece: "BN", esotericTarget: null },
  { hexNum: 14, piece: "WR", esotericTarget: null },
  { hexNum: 14, piece: "WP", esotericTarget: null },

  { hexNum: 15, piece: "WK", esotericTarget: 14 },
  { hexNum: 15, piece: "WQ", esotericTarget: 13 },
  { hexNum: 15, piece: "WB", esotericTarget: 11 },
  { hexNum: 15, piece: "WN", esotericTarget: 7 },
  { hexNum: 15, piece: "BR", esotericTarget: 31 },
  // GAME-LEVEL-DISABLED:{ hexNum: 15, piece: "BP", esotericTarget: 47 },
  { hexNum: 15, piece: "BK", esotericTarget: null },
  { hexNum: 15, piece: "BQ", esotericTarget: null },
  { hexNum: 15, piece: "BB", esotericTarget: null },
  { hexNum: 15, piece: "BN", esotericTarget: null },
  { hexNum: 15, piece: "WR", esotericTarget: null },
  { hexNum: 15, piece: "WP", esotericTarget: null },

  { hexNum: 16, piece: "BK", esotericTarget: 17 },
  { hexNum: 16, piece: "BQ", esotericTarget: 18 },
  { hexNum: 16, piece: "BB", esotericTarget: 20 },
  { hexNum: 16, piece: "BN", esotericTarget: 24 },
  { hexNum: 16, piece: "WR", esotericTarget: 0 },
  { hexNum: 16, piece: "BP", esotericTarget: 48 },
  { hexNum: 16, piece: "WK", esotericTarget: null },
  { hexNum: 16, piece: "WQ", esotericTarget: null },
  { hexNum: 16, piece: "WB", esotericTarget: null },
  { hexNum: 16, piece: "WN", esotericTarget: null },
  { hexNum: 16, piece: "BR", esotericTarget: null },
  { hexNum: 16, piece: "WP", esotericTarget: null },

  { hexNum: 17, piece: "WK", esotericTarget: 16 },
  { hexNum: 17, piece: "BQ", esotericTarget: 19 },
  { hexNum: 17, piece: "BB", esotericTarget: 21 },
  { hexNum: 17, piece: "BN", esotericTarget: 25 },
  { hexNum: 17, piece: "WR", esotericTarget: 1 },
  { hexNum: 17, piece: "BP", esotericTarget: 49 },
  { hexNum: 17, piece: "BK", esotericTarget: null },
  { hexNum: 17, piece: "WQ", esotericTarget: null },
  { hexNum: 17, piece: "WB", esotericTarget: null },
  { hexNum: 17, piece: "WN", esotericTarget: null },
  { hexNum: 17, piece: "BR", esotericTarget: null },
  { hexNum: 17, piece: "WP", esotericTarget: null },

  { hexNum: 18, piece: "BK", esotericTarget: 19 },
  { hexNum: 18, piece: "WQ", esotericTarget: 16 },
  { hexNum: 18, piece: "BB", esotericTarget: 22 },
  { hexNum: 18, piece: "BN", esotericTarget: 26 },
  { hexNum: 18, piece: "WR", esotericTarget: 2 },
  { hexNum: 18, piece: "BP", esotericTarget: 50 },
  { hexNum: 18, piece: "WK", esotericTarget: null },
  { hexNum: 18, piece: "BQ", esotericTarget: null },
  { hexNum: 18, piece: "WB", esotericTarget: null },
  { hexNum: 18, piece: "WN", esotericTarget: null },
  { hexNum: 18, piece: "BR", esotericTarget: null },
  { hexNum: 18, piece: "WP", esotericTarget: null },

  { hexNum: 19, piece: "WK", esotericTarget: 18 },
  { hexNum: 19, piece: "WQ", esotericTarget: 17 },
  { hexNum: 19, piece: "BB", esotericTarget: 23 },
  { hexNum: 19, piece: "BN", esotericTarget: 27 },
  { hexNum: 19, piece: "WR", esotericTarget: 3 },
  { hexNum: 19, piece: "BP", esotericTarget: 51 },
  { hexNum: 19, piece: "BK", esotericTarget: null },
  { hexNum: 19, piece: "BQ", esotericTarget: null },
  { hexNum: 19, piece: "WB", esotericTarget: null },
  { hexNum: 19, piece: "WN", esotericTarget: null },
  { hexNum: 19, piece: "BR", esotericTarget: null },
  { hexNum: 19, piece: "WP", esotericTarget: null },

  { hexNum: 20, piece: "BK", esotericTarget: 21 },
  { hexNum: 20, piece: "BQ", esotericTarget: 22 },
  { hexNum: 20, piece: "WB", esotericTarget: 16 },
  { hexNum: 20, piece: "BN", esotericTarget: 28 },
  { hexNum: 20, piece: "WR", esotericTarget: 4 },
  { hexNum: 20, piece: "BP", esotericTarget: 52 },
  { hexNum: 20, piece: "WK", esotericTarget: null },
  { hexNum: 20, piece: "WQ", esotericTarget: null },
  { hexNum: 20, piece: "BB", esotericTarget: null },
  { hexNum: 20, piece: "WN", esotericTarget: null },
  { hexNum: 20, piece: "BR", esotericTarget: null },
  { hexNum: 20, piece: "WP", esotericTarget: null },

  { hexNum: 21, piece: "WK", esotericTarget: 20 },
  { hexNum: 21, piece: "BQ", esotericTarget: 23 },
  { hexNum: 21, piece: "WB", esotericTarget: 17 },
  { hexNum: 21, piece: "BN", esotericTarget: 29 },
  { hexNum: 21, piece: "WR", esotericTarget: 5 },
  { hexNum: 21, piece: "BP", esotericTarget: 53 },
  { hexNum: 21, piece: "BK", esotericTarget: null },
  { hexNum: 21, piece: "WQ", esotericTarget: null },
  { hexNum: 21, piece: "BB", esotericTarget: null },
  { hexNum: 21, piece: "WN", esotericTarget: null },
  { hexNum: 21, piece: "BR", esotericTarget: null },
  { hexNum: 21, piece: "WP", esotericTarget: null },

  { hexNum: 22, piece: "BK", esotericTarget: 23 },
  { hexNum: 22, piece: "WQ", esotericTarget: 20 },
  { hexNum: 22, piece: "WB", esotericTarget: 18 },
  { hexNum: 22, piece: "BN", esotericTarget: 30 },
  { hexNum: 22, piece: "WR", esotericTarget: 6 },
  { hexNum: 22, piece: "BP", esotericTarget: 54 },
  { hexNum: 22, piece: "WK", esotericTarget: null },
  { hexNum: 22, piece: "BQ", esotericTarget: null },
  { hexNum: 22, piece: "BB", esotericTarget: null },
  { hexNum: 22, piece: "WN", esotericTarget: null },
  { hexNum: 22, piece: "BR", esotericTarget: null },
  { hexNum: 22, piece: "WP", esotericTarget: null },


  { hexNum: 23, piece: "WK", esotericTarget: 22 },
  { hexNum: 23, piece: "WQ", esotericTarget: 21 },
  { hexNum: 23, piece: "WB", esotericTarget: 19 },
  { hexNum: 23, piece: "BN", esotericTarget: 31 },
  { hexNum: 23, piece: "WR", esotericTarget: 7 },
  { hexNum: 23, piece: "BP", esotericTarget: 55 },
  { hexNum: 23, piece: "BK", esotericTarget: null },
  { hexNum: 23, piece: "BQ", esotericTarget: null },
  { hexNum: 23, piece: "BB", esotericTarget: null },
  { hexNum: 23, piece: "WN", esotericTarget: null },
  { hexNum: 23, piece: "BR", esotericTarget: null },
  { hexNum: 23, piece: "WP", esotericTarget: null },

  { hexNum: 24, piece: "BK", esotericTarget: 25 },
  { hexNum: 24, piece: "BQ", esotericTarget: 26 },
  { hexNum: 24, piece: "BB", esotericTarget: 28 },
  { hexNum: 24, piece: "WN", esotericTarget: 16 },
  { hexNum: 24, piece: "WR", esotericTarget: 8 },
  { hexNum: 24, piece: "BP", esotericTarget: 56 },
  { hexNum: 24, piece: "WK", esotericTarget: null },
  { hexNum: 24, piece: "WQ", esotericTarget: null },
  { hexNum: 24, piece: "WB", esotericTarget: null },
  { hexNum: 24, piece: "BN", esotericTarget: null },
  { hexNum: 24, piece: "BR", esotericTarget: null },
  { hexNum: 24, piece: "WP", esotericTarget: null },

  { hexNum: 25, piece: "WK", esotericTarget: 24 },
  { hexNum: 25, piece: "BQ", esotericTarget: 27 },
  { hexNum: 25, piece: "BB", esotericTarget: 29 },
  { hexNum: 25, piece: "WN", esotericTarget: 17 },
  { hexNum: 25, piece: "WR", esotericTarget: 9 },
  { hexNum: 25, piece: "BP", esotericTarget: 57 },
  { hexNum: 25, piece: "BK", esotericTarget: null },
  { hexNum: 25, piece: "WQ", esotericTarget: null },
  { hexNum: 25, piece: "WB", esotericTarget: null },
  { hexNum: 25, piece: "BN", esotericTarget: null },
  { hexNum: 25, piece: "BR", esotericTarget: null },
  { hexNum: 25, piece: "WP", esotericTarget: null },

  { hexNum: 26, piece: "BK", esotericTarget: 27 },
  { hexNum: 26, piece: "WQ", esotericTarget: 24 },
  { hexNum: 26, piece: "BB", esotericTarget: 30 },
  { hexNum: 26, piece: "WN", esotericTarget: 18 },
  { hexNum: 26, piece: "WR", esotericTarget: 10 },
  { hexNum: 26, piece: "BP", esotericTarget: 58 },
  { hexNum: 26, piece: "WK", esotericTarget: null },
  { hexNum: 26, piece: "BQ", esotericTarget: null },
  { hexNum: 26, piece: "WB", esotericTarget: null },
  { hexNum: 26, piece: "BN", esotericTarget: null },
  { hexNum: 26, piece: "BR", esotericTarget: null },
  { hexNum: 26, piece: "WP", esotericTarget: null },

  { hexNum: 27, piece: "WK", esotericTarget: 26 },
  { hexNum: 27, piece: "WQ", esotericTarget: 25 },
  { hexNum: 27, piece: "BB", esotericTarget: 31 },
  { hexNum: 27, piece: "WN", esotericTarget: 19 },
  { hexNum: 27, piece: "WR", esotericTarget: 11 },
  { hexNum: 27, piece: "BP", esotericTarget: 59 },
  { hexNum: 27, piece: "BK", esotericTarget: null },
  { hexNum: 27, piece: "BQ", esotericTarget: null },
  { hexNum: 27, piece: "WB", esotericTarget: null },
  { hexNum: 27, piece: "BN", esotericTarget: null },
  { hexNum: 27, piece: "BR", esotericTarget: null },
  { hexNum: 27, piece: "WP", esotericTarget: null },

  { hexNum: 28, piece: "BK", esotericTarget: 29 },
  { hexNum: 28, piece: "BQ", esotericTarget: 30 },
  { hexNum: 28, piece: "WB", esotericTarget: 24 },
  { hexNum: 28, piece: "WN", esotericTarget: 20 },
  { hexNum: 28, piece: "WR", esotericTarget: 12 },
  { hexNum: 28, piece: "BP", esotericTarget: 60 },
  { hexNum: 28, piece: "WK", esotericTarget: null },
  { hexNum: 28, piece: "WQ", esotericTarget: null },
  { hexNum: 28, piece: "BB", esotericTarget: null },
  { hexNum: 28, piece: "BN", esotericTarget: null },
  { hexNum: 28, piece: "BR", esotericTarget: null },
  { hexNum: 28, piece: "WP", esotericTarget: null },

  { hexNum: 29, piece: "WK", esotericTarget: 28 },
  { hexNum: 29, piece: "BQ", esotericTarget: 31 },
  { hexNum: 29, piece: "WB", esotericTarget: 25 },
  { hexNum: 29, piece: "WN", esotericTarget: 21 },
  { hexNum: 29, piece: "WR", esotericTarget: 13 },
  { hexNum: 29, piece: "BP", esotericTarget: 61 },
  { hexNum: 29, piece: "BK", esotericTarget: null },
  { hexNum: 29, piece: "WQ", esotericTarget: null },
  { hexNum: 29, piece: "BB", esotericTarget: null },
  { hexNum: 29, piece: "BN", esotericTarget: null },
  { hexNum: 29, piece: "BR", esotericTarget: null },
  { hexNum: 29, piece: "WP", esotericTarget: null },

  { hexNum: 30, piece: "BK", esotericTarget: 31 },
  { hexNum: 30, piece: "WQ", esotericTarget: 28 },
  { hexNum: 30, piece: "WB", esotericTarget: 26 },
  { hexNum: 30, piece: "WN", esotericTarget: 22 },
  { hexNum: 30, piece: "WR", esotericTarget: 14 },
  { hexNum: 30, piece: "BP", esotericTarget: 62 },
  { hexNum: 30, piece: "WK", esotericTarget: null },
  { hexNum: 30, piece: "BQ", esotericTarget: null },
  { hexNum: 30, piece: "BB", esotericTarget: null },
  { hexNum: 30, piece: "BN", esotericTarget: null },
  { hexNum: 30, piece: "BR", esotericTarget: null },
  { hexNum: 30, piece: "WP", esotericTarget: null },

  { hexNum: 31, piece: "WK", esotericTarget: 30 },
  { hexNum: 31, piece: "WQ", esotericTarget: 29 },
  { hexNum: 31, piece: "WB", esotericTarget: 27 },
  { hexNum: 31, piece: "WN", esotericTarget: 23 },
  { hexNum: 31, piece: "WR", esotericTarget: 15 },
  { hexNum: 31, piece: "BP", esotericTarget: 63 },
  { hexNum: 31, piece: "BK", esotericTarget: null },
  { hexNum: 31, piece: "BQ", esotericTarget: null },
  { hexNum: 31, piece: "BB", esotericTarget: null },
  { hexNum: 31, piece: "BN", esotericTarget: null },
  { hexNum: 31, piece: "BR", esotericTarget: null },
  { hexNum: 31, piece: "WP", esotericTarget: null },

  { hexNum: 32, piece: "BK", esotericTarget: 33 },
  { hexNum: 32, piece: "BQ", esotericTarget: 34 },
  { hexNum: 32, piece: "BB", esotericTarget: 36 },
  { hexNum: 32, piece: "BN", esotericTarget: 40 },
  { hexNum: 32, piece: "BR", esotericTarget: 48 },
  { hexNum: 32, piece: "WP", esotericTarget: 0 },
  { hexNum: 32, piece: "WK", esotericTarget: null },
  { hexNum: 32, piece: "WQ", esotericTarget: null },
  { hexNum: 32, piece: "WB", esotericTarget: null },
  { hexNum: 32, piece: "WN", esotericTarget: null },
  { hexNum: 32, piece: "WR", esotericTarget: null },
  { hexNum: 32, piece: "BP", esotericTarget: null },

  { hexNum: 33, piece: "WK", esotericTarget: 32 },
  { hexNum: 33, piece: "BQ", esotericTarget: 35 },
  { hexNum: 33, piece: "BB", esotericTarget: 37 },
  { hexNum: 33, piece: "BN", esotericTarget: 41 },
  { hexNum: 33, piece: "BR", esotericTarget: 49 },
  { hexNum: 33, piece: "WP", esotericTarget: 1 },
  { hexNum: 33, piece: "BK", esotericTarget: null },
  { hexNum: 33, piece: "WQ", esotericTarget: null },
  { hexNum: 33, piece: "WB", esotericTarget: null },
  { hexNum: 33, piece: "WN", esotericTarget: null },
  { hexNum: 33, piece: "WR", esotericTarget: null },
  { hexNum: 33, piece: "BP", esotericTarget: null },

  { hexNum: 34, piece: "BK", esotericTarget: 35 },
  { hexNum: 34, piece: "WQ", esotericTarget: 32 },
  { hexNum: 34, piece: "BB", esotericTarget: 38 },
  { hexNum: 34, piece: "BN", esotericTarget: 42 },
  { hexNum: 34, piece: "BR", esotericTarget: 50 },
  { hexNum: 34, piece: "WP", esotericTarget: 2 },
  { hexNum: 34, piece: "WK", esotericTarget: null },
  { hexNum: 34, piece: "BQ", esotericTarget: null },
  { hexNum: 34, piece: "WB", esotericTarget: null },
  { hexNum: 34, piece: "WN", esotericTarget: null },
  { hexNum: 34, piece: "WR", esotericTarget: null },
  { hexNum: 34, piece: "BP", esotericTarget: null },

  { hexNum: 35, piece: "WK", esotericTarget: 34 },
  { hexNum: 35, piece: "WQ", esotericTarget: 33 },
  { hexNum: 35, piece: "BB", esotericTarget: 39 },
  { hexNum: 35, piece: "BN", esotericTarget: 43 },
  { hexNum: 35, piece: "BR", esotericTarget: 51 },
  { hexNum: 35, piece: "WP", esotericTarget: 3 },
  { hexNum: 35, piece: "BK", esotericTarget: null },
  { hexNum: 35, piece: "BQ", esotericTarget: null },
  { hexNum: 35, piece: "WB", esotericTarget: null },
  { hexNum: 35, piece: "WN", esotericTarget: null },
  { hexNum: 35, piece: "WR", esotericTarget: null },
  { hexNum: 35, piece: "BP", esotericTarget: null },

  { hexNum: 36, piece: "BK", esotericTarget: 37 },
  { hexNum: 36, piece: "BQ", esotericTarget: 38 },
  { hexNum: 36, piece: "WB", esotericTarget: 32 },
  { hexNum: 36, piece: "BN", esotericTarget: 44 },
  { hexNum: 36, piece: "BR", esotericTarget: 52 },
  { hexNum: 36, piece: "WP", esotericTarget: 4 },
  { hexNum: 36, piece: "WK", esotericTarget: null },
  { hexNum: 36, piece: "WQ", esotericTarget: null },
  { hexNum: 36, piece: "BB", esotericTarget: null },
  { hexNum: 36, piece: "WN", esotericTarget: null },
  { hexNum: 36, piece: "WR", esotericTarget: null },
  { hexNum: 36, piece: "BP", esotericTarget: null },

  { hexNum: 37, piece: "WK", esotericTarget: 36 },
  { hexNum: 37, piece: "BQ", esotericTarget: 39 },
  { hexNum: 37, piece: "WB", esotericTarget: 33 },
  { hexNum: 37, piece: "BN", esotericTarget: 45 },
  { hexNum: 37, piece: "BR", esotericTarget: 53 },
  { hexNum: 37, piece: "WP", esotericTarget: 5 },
  { hexNum: 37, piece: "BK", esotericTarget: null },
  { hexNum: 37, piece: "WQ", esotericTarget: null },
  { hexNum: 37, piece: "BB", esotericTarget: null },
  { hexNum: 37, piece: "WN", esotericTarget: null },
  { hexNum: 37, piece: "WR", esotericTarget: null },
  { hexNum: 37, piece: "BP", esotericTarget: null },

  { hexNum: 38, piece: "BK", esotericTarget: 39 },
  { hexNum: 38, piece: "WQ", esotericTarget: 36 },
  { hexNum: 38, piece: "WB", esotericTarget: 34 },
  { hexNum: 38, piece: "BN", esotericTarget: 46 },
  { hexNum: 38, piece: "BR", esotericTarget: 54 },
  { hexNum: 38, piece: "WP", esotericTarget: 6 },
  { hexNum: 38, piece: "WK", esotericTarget: null },
  { hexNum: 38, piece: "BQ", esotericTarget: null },
  { hexNum: 38, piece: "BB", esotericTarget: null },
  { hexNum: 38, piece: "WN", esotericTarget: null },
  { hexNum: 38, piece: "WR", esotericTarget: null },
  { hexNum: 38, piece: "BP", esotericTarget: null },

  { hexNum: 39, piece: "WK", esotericTarget: 38 },
  { hexNum: 39, piece: "WQ", esotericTarget: 37 },
  { hexNum: 39, piece: "WB", esotericTarget: 35 },
  { hexNum: 39, piece: "BN", esotericTarget: 47 },
  { hexNum: 39, piece: "BR", esotericTarget: 55 },
  { hexNum: 39, piece: "WP", esotericTarget: 7 },
  { hexNum: 39, piece: "BK", esotericTarget: null },
  { hexNum: 39, piece: "BQ", esotericTarget: null },
  { hexNum: 39, piece: "BB", esotericTarget: null },
  { hexNum: 39, piece: "WN", esotericTarget: null },
  { hexNum: 39, piece: "WR", esotericTarget: null },
  { hexNum: 39, piece: "BP", esotericTarget: null },

  { hexNum: 40, piece: "BK", esotericTarget: 41 },
  { hexNum: 40, piece: "BQ", esotericTarget: 42 },
  { hexNum: 40, piece: "BB", esotericTarget: 44 },
  { hexNum: 40, piece: "WN", esotericTarget: 32 },
  { hexNum: 40, piece: "BR", esotericTarget: 56 },
  { hexNum: 40, piece: "WP", esotericTarget: 8 },
  { hexNum: 40, piece: "WK", esotericTarget: null },
  { hexNum: 40, piece: "WQ", esotericTarget: null },
  { hexNum: 40, piece: "WB", esotericTarget: null },
  { hexNum: 40, piece: "BN", esotericTarget: null },
  { hexNum: 40, piece: "WR", esotericTarget: null },
  { hexNum: 40, piece: "BP", esotericTarget: null },

  { hexNum: 41, piece: "WK", esotericTarget: 40 },
  { hexNum: 41, piece: "BQ", esotericTarget: 43 },
  { hexNum: 41, piece: "BB", esotericTarget: 45 },
  { hexNum: 41, piece: "WN", esotericTarget: 33 },
  { hexNum: 41, piece: "BR", esotericTarget: 57 },
  { hexNum: 41, piece: "WP", esotericTarget: 9 },
  { hexNum: 41, piece: "BK", esotericTarget: null },
  { hexNum: 41, piece: "WQ", esotericTarget: null },
  { hexNum: 41, piece: "WB", esotericTarget: null },
  { hexNum: 41, piece: "BN", esotericTarget: null },
  { hexNum: 41, piece: "WR", esotericTarget: null },
  { hexNum: 41, piece: "BP", esotericTarget: null },

  { hexNum: 42, piece: "BK", esotericTarget: 43 },
  { hexNum: 42, piece: "WQ", esotericTarget: 40 },
  { hexNum: 42, piece: "BB", esotericTarget: 46 },
  { hexNum: 42, piece: "WN", esotericTarget: 34 },
  { hexNum: 42, piece: "BR", esotericTarget: 58 },
  { hexNum: 42, piece: "WP", esotericTarget: 10 },
  { hexNum: 42, piece: "WK", esotericTarget: null },
  { hexNum: 42, piece: "BQ", esotericTarget: null },
  { hexNum: 42, piece: "WB", esotericTarget: null },
  { hexNum: 42, piece: "BN", esotericTarget: null },
  { hexNum: 42, piece: "WR", esotericTarget: null },
  { hexNum: 42, piece: "BP", esotericTarget: null },

  { hexNum: 43, piece: "WK", esotericTarget: 42 },
  { hexNum: 43, piece: "WQ", esotericTarget: 41 },
  { hexNum: 43, piece: "BB", esotericTarget: 47 },
  { hexNum: 43, piece: "WN", esotericTarget: 35 },
  { hexNum: 43, piece: "BR", esotericTarget: 59 },
  { hexNum: 43, piece: "WP", esotericTarget: 11 },
  { hexNum: 43, piece: "BK", esotericTarget: null },
  { hexNum: 43, piece: "BQ", esotericTarget: null },
  { hexNum: 43, piece: "WB", esotericTarget: null },
  { hexNum: 43, piece: "BN", esotericTarget: null },
  { hexNum: 43, piece: "WR", esotericTarget: null },
  { hexNum: 43, piece: "BP", esotericTarget: null },

  { hexNum: 44, piece: "BK", esotericTarget: 45 },
  { hexNum: 44, piece: "BQ", esotericTarget: 46 },
  { hexNum: 44, piece: "WB", esotericTarget: 40 },
  { hexNum: 44, piece: "WN", esotericTarget: 36 },
  { hexNum: 44, piece: "BR", esotericTarget: 60 },
  { hexNum: 44, piece: "WP", esotericTarget: 12 },
  { hexNum: 44, piece: "WK", esotericTarget: null },
  { hexNum: 44, piece: "WQ", esotericTarget: null },
  { hexNum: 44, piece: "BB", esotericTarget: null },
  { hexNum: 44, piece: "BN", esotericTarget: null },
  { hexNum: 44, piece: "WR", esotericTarget: null },
  { hexNum: 44, piece: "BP", esotericTarget: null },

  { hexNum: 45, piece: "WK", esotericTarget: 44 },
  { hexNum: 45, piece: "BQ", esotericTarget: 47 },
  { hexNum: 45, piece: "WB", esotericTarget: 41 },
  { hexNum: 45, piece: "WN", esotericTarget: 37 },
  { hexNum: 45, piece: "BR", esotericTarget: 61 },
  { hexNum: 45, piece: "WP", esotericTarget: 13 },
  { hexNum: 45, piece: "BK", esotericTarget: null },
  { hexNum: 45, piece: "WQ", esotericTarget: null },
  { hexNum: 45, piece: "BB", esotericTarget: null },
  { hexNum: 45, piece: "BN", esotericTarget: null },
  { hexNum: 45, piece: "WR", esotericTarget: null },
  { hexNum: 45, piece: "BP", esotericTarget: null },

  { hexNum: 46, piece: "BK", esotericTarget: 47 },
  { hexNum: 46, piece: "WQ", esotericTarget: 44 },
  { hexNum: 46, piece: "WB", esotericTarget: 42 },
  { hexNum: 46, piece: "WN", esotericTarget: 38 },
  { hexNum: 46, piece: "BR", esotericTarget: 62 },
  { hexNum: 46, piece: "WP", esotericTarget: 14 },
  { hexNum: 46, piece: "WK", esotericTarget: null },
  { hexNum: 46, piece: "BQ", esotericTarget: null },
  { hexNum: 46, piece: "BB", esotericTarget: null },
  { hexNum: 46, piece: "BN", esotericTarget: null },
  { hexNum: 46, piece: "WR", esotericTarget: null },
  { hexNum: 46, piece: "BP", esotericTarget: null },

  { hexNum: 47, piece: "WK", esotericTarget: 46 },
  { hexNum: 47, piece: "WQ", esotericTarget: 45 },
  { hexNum: 47, piece: "WB", esotericTarget: 43 },
  { hexNum: 47, piece: "WN", esotericTarget: 39 },
  { hexNum: 47, piece: "BR", esotericTarget: 63 },
  { hexNum: 47, piece: "WP", esotericTarget: 15 },
  { hexNum: 47, piece: "BK", esotericTarget: null },
  { hexNum: 47, piece: "BQ", esotericTarget: null },
  { hexNum: 47, piece: "BB", esotericTarget: null },
  { hexNum: 47, piece: "BN", esotericTarget: null },
  { hexNum: 47, piece: "WR", esotericTarget: null },
  { hexNum: 47, piece: "BP", esotericTarget: null },

  { hexNum: 48, piece: "BK", esotericTarget: 49 },
  { hexNum: 48, piece: "BQ", esotericTarget: 50 },
  { hexNum: 48, piece: "BB", esotericTarget: 52 },
  { hexNum: 48, piece: "BN", esotericTarget: 56 },
  { hexNum: 48, piece: "WR", esotericTarget: 32 },
  // GAME-LEVEL-DISABLED:{ hexNum: 48, piece: "WP", esotericTarget: 16 },
  { hexNum: 48, piece: "WK", esotericTarget: null },
  { hexNum: 48, piece: "WQ", esotericTarget: null },
  { hexNum: 48, piece: "WB", esotericTarget: null },
  { hexNum: 48, piece: "WN", esotericTarget: null },
  { hexNum: 48, piece: "BR", esotericTarget: null },
  { hexNum: 48, piece: "BP", esotericTarget: null },

  { hexNum: 49, piece: "WK", esotericTarget: 48 },
  { hexNum: 49, piece: "BQ", esotericTarget: 51 },
  { hexNum: 49, piece: "BB", esotericTarget: 53 },
  { hexNum: 49, piece: "BN", esotericTarget: 57 },
  { hexNum: 49, piece: "WR", esotericTarget: 33 },
  // GAME-LEVEL-DISABLED:{ hexNum: 49, piece: "WP", esotericTarget: 17 },
  { hexNum: 49, piece: "BK", esotericTarget: null },
  { hexNum: 49, piece: "WQ", esotericTarget: null },
  { hexNum: 49, piece: "WB", esotericTarget: null },
  { hexNum: 49, piece: "WN", esotericTarget: null },
  { hexNum: 49, piece: "BR", esotericTarget: null },
  { hexNum: 49, piece: "BP", esotericTarget: null },

  { hexNum: 50, piece: "BK", esotericTarget: 51 },
  { hexNum: 50, piece: "WQ", esotericTarget: 48 },
  { hexNum: 50, piece: "BB", esotericTarget: 54 },
  { hexNum: 50, piece: "BN", esotericTarget: 58 },
  { hexNum: 50, piece: "WR", esotericTarget: 34 },
  // GAME-LEVEL-DISABLED:{ hexNum: 50, piece: "WP", esotericTarget: 18 },
  { hexNum: 50, piece: "WK", esotericTarget: null },
  { hexNum: 50, piece: "BQ", esotericTarget: null },
  { hexNum: 50, piece: "WB", esotericTarget: null },
  { hexNum: 50, piece: "WN", esotericTarget: null },
  { hexNum: 50, piece: "BR", esotericTarget: null },
  { hexNum: 50, piece: "BP", esotericTarget: null },

  { hexNum: 51, piece: "WK", esotericTarget: 50 },
  { hexNum: 51, piece: "WQ", esotericTarget: 49 },
  { hexNum: 51, piece: "BB", esotericTarget: 55 },
  { hexNum: 51, piece: "BN", esotericTarget: 59 },
  { hexNum: 51, piece: "WR", esotericTarget: 35 },
  // GAME-LEVEL-DISABLED:{ hexNum: 51, piece: "WP", esotericTarget: 19 },
  { hexNum: 51, piece: "BK", esotericTarget: null },
  { hexNum: 51, piece: "BQ", esotericTarget: null },
  { hexNum: 51, piece: "WB", esotericTarget: null },
  { hexNum: 51, piece: "WN", esotericTarget: null },
  { hexNum: 51, piece: "BR", esotericTarget: null },
  { hexNum: 51, piece: "BP", esotericTarget: null },

  { hexNum: 52, piece: "BK", esotericTarget: 53 },
  { hexNum: 52, piece: "BQ", esotericTarget: 54 },
  { hexNum: 52, piece: "WB", esotericTarget: 48 },
  { hexNum: 52, piece: "BN", esotericTarget: 60 },
  { hexNum: 52, piece: "WR", esotericTarget: 36 },
  // GAME-LEVEL-DISABLED:{ hexNum: 52, piece: "WP", esotericTarget: 20 },
  { hexNum: 52, piece: "WK", esotericTarget: null },
  { hexNum: 52, piece: "WQ", esotericTarget: null },
  { hexNum: 52, piece: "BB", esotericTarget: null },
  { hexNum: 52, piece: "WN", esotericTarget: null },
  { hexNum: 52, piece: "BR", esotericTarget: null },
  { hexNum: 52, piece: "BP", esotericTarget: null },

  { hexNum: 53, piece: "WK", esotericTarget: 52 },
  { hexNum: 53, piece: "BQ", esotericTarget: 55 },
  { hexNum: 53, piece: "WB", esotericTarget: 49 },
  { hexNum: 53, piece: "BN", esotericTarget: 61 },
  { hexNum: 53, piece: "WR", esotericTarget: 37 },
  // GAME-LEVEL-DISABLED:{ hexNum: 53, piece: "WP", esotericTarget: 21 },
  { hexNum: 53, piece: "BK", esotericTarget: null },
  { hexNum: 53, piece: "WQ", esotericTarget: null },
  { hexNum: 53, piece: "BB", esotericTarget: null },
  { hexNum: 53, piece: "WN", esotericTarget: null },
  { hexNum: 53, piece: "BR", esotericTarget: null },
  { hexNum: 53, piece: "BP", esotericTarget: null },

  { hexNum: 54, piece: "BK", esotericTarget: 55 },
  { hexNum: 54, piece: "WQ", esotericTarget: 52 },
  { hexNum: 54, piece: "WB", esotericTarget: 50 },
  { hexNum: 54, piece: "BN", esotericTarget: 62 },
  { hexNum: 54, piece: "WR", esotericTarget: 38 },
  // GAME-LEVEL-DISABLED:{ hexNum: 54, piece: "WP", esotericTarget: 22 },
  { hexNum: 54, piece: "WK", esotericTarget: 55 },
  { hexNum: 54, piece: "BQ", esotericTarget: 52 },
  { hexNum: 54, piece: "BB", esotericTarget: 50 },
  { hexNum: 54, piece: "WN", esotericTarget: 62 },
  { hexNum: 54, piece: "BR", esotericTarget: 38 },
  { hexNum: 54, piece: "BP", esotericTarget: 22 },

  { hexNum: 55, piece: "WK", esotericTarget: 54 },
  { hexNum: 55, piece: "WQ", esotericTarget: 53 },
  { hexNum: 55, piece: "WB", esotericTarget: 51 },
  { hexNum: 55, piece: "BN", esotericTarget: 63 },
  { hexNum: 55, piece: "WR", esotericTarget: 39 },
  // GAME-LEVEL-DISABLED:{ hexNum: 55, piece: "WP", esotericTarget: 23 },
  { hexNum: 55, piece: "BK", esotericTarget: 54 },
  { hexNum: 55, piece: "BQ", esotericTarget: 53 },
  { hexNum: 55, piece: "BB", esotericTarget: 51 },
  { hexNum: 55, piece: "WN", esotericTarget: 63 },
  { hexNum: 55, piece: "BR", esotericTarget: 39 },
  { hexNum: 55, piece: "BP", esotericTarget: 23 },

  { hexNum: 56, piece: "BK", esotericTarget: 57 },
  { hexNum: 56, piece: "BQ", esotericTarget: 58 },
  { hexNum: 56, piece: "BB", esotericTarget: 60 },
  { hexNum: 56, piece: "WN", esotericTarget: 48 },
  { hexNum: 56, piece: "WR", esotericTarget: 40 },
  { hexNum: 56, piece: "WP", esotericTarget: 24 },
  { hexNum: 56, piece: "WK", esotericTarget: 57 },
  { hexNum: 56, piece: "WQ", esotericTarget: 58 },
  { hexNum: 56, piece: "WB", esotericTarget: 60 },
  { hexNum: 56, piece: "BN", esotericTarget: 48 },
  { hexNum: 56, piece: "BR", esotericTarget: 40 },
  { hexNum: 56, piece: "BP", esotericTarget: 24 },

  { hexNum: 57, piece: "WK", esotericTarget: 56 },
  { hexNum: 57, piece: "BQ", esotericTarget: 61 },
  { hexNum: 57, piece: "BB", esotericTarget: 61 },
  { hexNum: 57, piece: "WN", esotericTarget: 49 },
  { hexNum: 57, piece: "WR", esotericTarget: 41 },
  { hexNum: 57, piece: "WP", esotericTarget: 25 },
  { hexNum: 57, piece: "BK", esotericTarget: 56 },
  { hexNum: 57, piece: "WQ", esotericTarget: 61 },
  { hexNum: 57, piece: "WB", esotericTarget: 61 },
  { hexNum: 57, piece: "BN", esotericTarget: 49 },
  { hexNum: 57, piece: "BR", esotericTarget: 41 },
  { hexNum: 57, piece: "BP", esotericTarget: 25 },

  { hexNum: 58, piece: "BK", esotericTarget: 59 },
  { hexNum: 58, piece: "WQ", esotericTarget: 56 },
  { hexNum: 58, piece: "BB", esotericTarget: 62 },
  { hexNum: 58, piece: "WN", esotericTarget: 50 },
  { hexNum: 58, piece: "WR", esotericTarget: 42 },
  { hexNum: 58, piece: "WP", esotericTarget: 26 },
  { hexNum: 58, piece: "WK", esotericTarget: 59 },
  { hexNum: 58, piece: "BQ", esotericTarget: 56 },
  { hexNum: 58, piece: "WB", esotericTarget: 62 },
  { hexNum: 58, piece: "BN", esotericTarget: 50 },
  { hexNum: 58, piece: "BR", esotericTarget: 42 },
  { hexNum: 58, piece: "BP", esotericTarget: 26 },

  { hexNum: 59, piece: "WK", esotericTarget: 58 },
  { hexNum: 59, piece: "WQ", esotericTarget: 57 },
  { hexNum: 59, piece: "BB", esotericTarget: 63 },
  { hexNum: 59, piece: "WN", esotericTarget: 51 },
  { hexNum: 59, piece: "WR", esotericTarget: 43 },
  { hexNum: 59, piece: "WP", esotericTarget: 27 },
  { hexNum: 59, piece: "BK", esotericTarget: null },
  { hexNum: 59, piece: "BQ", esotericTarget: null },
  { hexNum: 59, piece: "WB", esotericTarget: null },
  { hexNum: 59, piece: "BN", esotericTarget: null },
  { hexNum: 59, piece: "BR", esotericTarget: null },
  { hexNum: 59, piece: "BP", esotericTarget: null },

  { hexNum: 60, piece: "BK", esotericTarget: 61 },
  { hexNum: 60, piece: "BQ", esotericTarget: 62 },
  { hexNum: 60, piece: "WB", esotericTarget: 56 },
  { hexNum: 60, piece: "WN", esotericTarget: 52 },
  { hexNum: 60, piece: "WR", esotericTarget: 44 },
  { hexNum: 60, piece: "WP", esotericTarget: 28 },
  { hexNum: 60, piece: "BK", esotericTarget: null },
  { hexNum: 60, piece: "BQ", esotericTarget: null },
  { hexNum: 60, piece: "WB", esotericTarget: null },
  { hexNum: 60, piece: "BN", esotericTarget: null },
  { hexNum: 60, piece: "BR", esotericTarget: null },
  { hexNum: 60, piece: "BP", esotericTarget: null },

  { hexNum: 61, piece: "WK", esotericTarget: 60 },
  { hexNum: 61, piece: "BQ", esotericTarget: 63 },
  { hexNum: 61, piece: "WB", esotericTarget: 57 },
  { hexNum: 61, piece: "WN", esotericTarget: 53 },
  { hexNum: 61, piece: "WR", esotericTarget: 45 },
  { hexNum: 61, piece: "WP", esotericTarget: 29 },
  { hexNum: 61, piece: "BK", esotericTarget: null },
  { hexNum: 61, piece: "WQ", esotericTarget: null },
  { hexNum: 61, piece: "BB", esotericTarget: null },
  { hexNum: 61, piece: "BN", esotericTarget: null },
  { hexNum: 61, piece: "BR", esotericTarget: null },
  { hexNum: 61, piece: "BP", esotericTarget: null },

  { hexNum: 62, piece: "BK", esotericTarget: 63 },
  { hexNum: 62, piece: "WQ", esotericTarget: 60 },
  { hexNum: 62, piece: "WB", esotericTarget: 58 },
  { hexNum: 62, piece: "WN", esotericTarget: 54 },
  { hexNum: 62, piece: "WR", esotericTarget: 46 },
  { hexNum: 62, piece: "WP", esotericTarget: 30 },
  { hexNum: 62, piece: "WK", esotericTarget: null },
  { hexNum: 62, piece: "BQ", esotericTarget: null },
  { hexNum: 62, piece: "BB", esotericTarget: null },
  { hexNum: 62, piece: "BN", esotericTarget: null },
  { hexNum: 62, piece: "BR", esotericTarget: null },
  { hexNum: 62, piece: "BP", esotericTarget: null },

  { hexNum: 63, piece: "WK", esotericTarget: 62 },
  { hexNum: 63, piece: "WQ", esotericTarget: 61 },
  { hexNum: 63, piece: "WB", esotericTarget: 59 },
  { hexNum: 63, piece: "WN", esotericTarget: 55 },
  { hexNum: 63, piece: "WR", esotericTarget: 47 },
  { hexNum: 63, piece: "WP", esotericTarget: 31 },
  { hexNum: 63, piece: "BK", esotericTarget: null },
  { hexNum: 63, piece: "BQ", esotericTarget: null },
  { hexNum: 63, piece: "BB", esotericTarget: null },
  { hexNum: 63, piece: "BN", esotericTarget: null },
  { hexNum: 63, piece: "BR", esotericTarget: null },
  { hexNum: 63, piece: "BP", esotericTarget: null },

];
export const esotericMoves_backup = [...esotericMoves];

export const esotericMovesByHexNum = {};
for (const entry of esotericMoves) {
  const { hexNum, piece, esotericTarget } = entry;
  if (!esotericMovesByHexNum[hexNum]) esotericMovesByHexNum[hexNum] = {};
  let coord = null;
  if (esotericTarget != null) {
    const target = positionMap.find(p => p.hexNum === esotericTarget);
    coord = target ? target.coord : null;
  }
  esotericMovesByHexNum[hexNum][piece] = { esotericTarget, coord };
}

/**
 * Returns the esoteric target info for a given piece and hexNum using the nested lookup structure.
 * @param {string} piece - Piece code (e.g. 'BP', 'WK')
 * @param {number} hexNum - The hexagram number of the current square
 * @returns {object|null} { hexNum, row, col, coord } or null if no esoteric move
 */

export function getEsotericTargetIndex(pieceCode, hexNum) {
  console.log('[esotericMoves] getEsotericTargetIndex called:', { pieceCode, hexNum });
  const move = esotericMoves.find(m => m.piece === pieceCode && m.hexNum === hexNum);
  if (!move) {
    console.log('[esotericMoves] No esoteric move found for', { pieceCode, hexNum });
    return null;
  }
  console.log('[esotericMoves] Esoteric target index:', move.esotericTarget);
  return move.esotericTarget;
}
export function handleEsotericMove(pieceCode, hexNum, boardState) {
  console.log('[esotericMoves] handleEsotericMove called:', { pieceCode, hexNum });
  const esotericTarget = getEsotericTargetIndex(pieceCode, hexNum);
  if (esotericTarget === null) {
    console.log('[esotericMoves] No esoteric target for', { pieceCode, hexNum });
    return boardState; // no change
  }

  const currentPos = positionMap.find(pos => pos.index === hexNum);
  const targetPos = positionMap.find(pos => pos.index === esotericTarget);

  if (!currentPos || !targetPos) {
    console.log('[esotericMoves] Invalid current or target position:', { currentPos, targetPos });
    return boardState; // no change
  }

  // If the target already has the piece, or the move is a no-op, return the original state
  if (
    boardState[targetPos.row][targetPos.col] === pieceCode &&
    boardState[currentPos.row][currentPos.col] === null
  ) {
    console.log('[esotericMoves] No-op move detected, returning original state');
    return boardState;
  }

  // Deep copy the board state
  const newState = boardState.map(row => row.slice());

  // Move piece to esoteric target
  newState[currentPos.row][currentPos.col] = null;
  newState[targetPos.row][targetPos.col] = pieceCode;

  console.log('[esotericMoves] Piece moved to esoteric target:', { from: currentPos, to: targetPos });
  return newState;
}