// Reference Portal Hexagram Keywords
// Maps hexagram number → keyword for lookup only
// Pure data structure for binary-based reference display

export const hexByBinary = {
  0: { keyword: 'Essence' },
  1: { keyword: 'Revelation' },
  2: { keyword: 'Intuition' },
  3: { keyword: 'Emanation' },
  4: { keyword: 'Identification' },
  5: { keyword: 'Interpretation' },
  6: { keyword: 'Cultivation' },
  7: { keyword: 'Orientation' },
  8: { keyword: 'Devotion' },
  9: { keyword: 'Sensitization' },
  10: { keyword: 'Incongruity' },
  11: { keyword: 'Projection' },
  12: { keyword: 'Authenticity' },
  13: { keyword: 'Induction' },
  14: { keyword: 'Inhibition' },
  15: { keyword: 'Emancipation' },
  16: { keyword: 'Conceptualization' },
  17: { keyword: 'Congruity' },
  18: { keyword: 'Certainty' },
  19: { keyword: 'Instruction' },
  20: { keyword: 'Tradition' },
  21: { keyword: 'Rationality' },
  22: { keyword: 'Preconception' },
  23: { keyword: 'Noninterference' },
  24: { keyword: 'Participation' },
  25: { keyword: 'Persuasion' },
  26: { keyword: 'Ambition' },
  27: { keyword: 'Provocation' },
  28: { keyword: 'Regeneration' },
  29: { keyword: 'Eradication' },
  30: { keyword: 'Evolution' },
  31: { keyword: 'Transcendence' },
  32: { keyword: 'Experience' },
  33: { keyword: 'Compulsion' },
  34: { keyword: 'Reflection' },
  35: { keyword: 'Propagation' },
  36: { keyword: 'Resilience' },
  37: { keyword: 'Potentiality' },
  38: { keyword: 'Utilization' },
  39: { keyword: 'Individuation' },
  40: { keyword: 'Confrontation' },
  41: { keyword: 'Gratification' },
  42: { keyword: 'Irrationality' },
  43: { keyword: 'Nonsublimation' },
  44: { keyword: 'Improvisation' },
  45: { keyword: 'Uncertainty' },
  46: { keyword: 'Specialization' },
  47: { keyword: 'Synchronization' },
  48: { keyword: 'Internalization' },
  49: { keyword: 'Communication' },
  50: { keyword: 'Recollection' },
  51: { keyword: 'Concentration' },
  52: { keyword: 'Self-Sufficiency' },
  53: { keyword: 'Disorientation' },
  54: { keyword: 'Extinction' },
  55: { keyword: 'Nonspecialization' },
  56: { keyword: 'Recapitulation' },
  57: { keyword: 'Celebration' },
  58: { keyword: 'Compliance' },
  59: { keyword: 'Inspiration' },
  60: { keyword: 'Reintegration' },
  61: { keyword: 'Habituation' },
  62: { keyword: 'Disintegration' },
  63: { keyword: 'Existence' }
};

// Lookup function to get keyword from hexagram number
export function getKeywordFromHex(hexNum) {
  return hexByBinary[hexNum]?.keyword || 'Unknown';
}